### ISSUE TITLE
Missing data in dataset?

### ISSUE THREAD

**Issue by ChenyangLiu** [lixx2938/MegaDepth#1]
Hi,

I've downloaded your dataset on the website, but I found that there is no data for ordinal depth which is mentioned in section 3.3 of the paper. Where can I get that data? Thank you.

**Comment by lixx2938** [comment]
Hi, I think I updated the dataset after first time I released the dataset, please download it again and see if there is an ordinal depth (also see http://www.cs.cornell.edu/projects/megadepth/dataset/Megadepth_v1/README.md, since ordinal depth and dense map are stored as the same name in HDF5).
