### ISSUE TITLE
Data cannot download

### ISSUE THREAD

**Issue by ryf1123** [lixx2938/MegaDepth#35]
Hi, thank you for your dataset. 

However, I have a problem downloading it. It seems that it is too big. So, could you please split the dataset into several parts, or upload the dataset into other platform like google drive, or provide some smaller sample cases?

Many thanks for your help!

**Comment by non-void** [comment]
Same issue here, could you please split the dataset into smaller size?

**Comment by ryf1123** [comment]
> Same issue here, could you please split the dataset into smaller size?

Hi, I've successfully downloaded this dataset. Maybe I can share it with google drive.

**Comment by ryf1123** [comment]
> Same issue here, could you please split the dataset into smaller size?

Can you try this link? https://drive.google.com/open?id=1nA299ZEH0kYunkhEfDWq2ay32t4QQhP2

**Comment by LoFaiTh** [comment]
> > Same issue here, could you please split the dataset into smaller size?
> 
> Can you try this link? https://drive.google.com/open?id=1nA299ZEH0kYunkhEfDWq2ay32t4QQhP2

hi, can you please share 199G version dataset on google drive too?

**Comment by pengzhi1998** [comment]
> > Same issue here, could you please split the dataset into smaller size?
> 
> Can you try this link? https://drive.google.com/open?id=1nA299ZEH0kYunkhEfDWq2ay32t4QQhP2

Hi Yufan, it seems that the link cannot work. Could you please share the dataset again?

**Comment by superzrx** [comment]
hi Yufan, same problem here, need help @ryf1123

**Comment by CJCHEN1230** [comment]
Same problem

**Comment by min-hieu-netropy** [comment]
any update on this?
