### ISSUE TITLE
Dataset links are dead

### ISSUE THREAD

**Issue by l0stpenguin** [lixx2938/MegaDepth#41]
I cannot download the 199GB dataset from the website. All download links are dead. Does anyone have an alternative link for the dataset?
![Screenshot 2020-06-15 at 11 44 25](https://user-images.githubusercontent.com/17478561/84631013-c8614c00-aefd-11ea-8aec-73b4da821cdb.png)
![Screenshot 2020-06-15 at 11 44 34](https://user-images.githubusercontent.com/17478561/84631022-cc8d6980-aefd-11ea-9018-4753540448e7.png)

**Comment by pengzhi1998** [comment]
Hi, did you solve this?

I'm facing the similar problem. And the dataset is so big and I don't have a stable connect.
