### ISSUE TITLE
Change the size of the input image

### ISSUE THREAD

**Issue by yanyu-holo** [lixx2938/MegaDepth#44]
Hello, your work is very helpful to me. I want the input RGB image and the output depth map to be 1000 * 1000 pixels. How can I change the code?

**Comment by zhengqili** [comment]
our current method only supports the size of multiple of 64，you might need to resize the image before feeding the network and resize predicted depth back to 1000x1000

**Comment by yanyu-holo** [comment]
> Thank you for your reply. If I understand correctly, your method is to get relative depth, not absolute depth, right?

**Comment by zhengqili** [comment]
Hi, yes. Only relative depth, up to scale.
